version: '3.8'

services:
  backend:
    build: backend
    restart: always
    hostname: backend-host
    volumes:
      - ./backend:/app
    #ports:
    #  - "8000:8000"
    networks:
      - student-network

  frontend:
    build: frontend
    restart: always
    hostname: frontend-host
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3001"
    environment:
      - BACKENDURL=http://backend-host:8000
    depends_on:
      - backend
    networks:
      - student-network

networks:
  student-network: 
